### ISSUE TITLE
deviance "function not found"

### ISSUE THREAD

**Issue by bdemeshev** [RevolutionAnalytics/RRO#112]
```
library("ggplot2")
model <- lm(data=diamonds, price~carat + clarity)
devianсe(model)
```

gives:

Error: could not find function "devianсe"

**Comment by andrie** [comment]
If I copy your code, that letter that looks like a `c` is some unicode character:

```r
> devianсe(model)
Error: unexpected input in "devian\"
```

If I use `deviance()` with all ASCII, I can't reproduce your problem:

```r
> deviance(model)
[1] 90263944583
```

**Comment by revodavid** [comment]
Hi Boris,

The code works fine if I TYPE the following on my system:

> library("ggplot2")
> model <- lm(data=diamonds, price~carat + clarity)
> deviance(model)
[1] 90263944583

However, if I cut-and-paste your last line I get this error:

> devianсe(model)
Error: could not find function "devianсe"

There's actually a typo in your text -- the "c" is actually a foreign
character. If you manually type "deviance" at the command line instead of
cut-and-pasting it should work fine.

The error is in wherever you found that text, not RRO.

Thanks,
# David




-- 
David M Smith <david@revolutionanalytics.com>
Chief Community Officer, Revolution Analytics
http://blog.revolutionanalytics.com
Tel: +1 (650) 646-9523 (Chicago IL, USA)
Twitter: @revodavid

**Comment by bdemeshev** [comment]
sorry for bothering you!
