### ISSUE TITLE
RRO Welcome Screen has http:// instead https:// address

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#207]
![welcome](https://cloud.githubusercontent.com/assets/8481597/8881411/363d3ce6-3205-11e5-8382-3ff273675e57.png)

**Comment by j-martens** [comment]
Also applies to the URLS on Windows:

Welcome to the Revolution R Open Installer

Revolution R Open is an enhanced distribution of R from Revolution Analytics. 
For information about Revolution R Open, visit http://mran.revolutionanalytics.com.

Revolution R Open is based on R, Copyright (C) The R Foundation for Statistical Computing. 
Visit www.r-project.org for information about the R Project. 
R is the creation of many contributors, for details visit http://www.r-project.org/contributors.html.

**Comment by j-martens** [comment]
Looks good for Windows.

Still needs to be verified in the OS X installer.

**Comment by j-martens** [comment]
Still not fixed in OS X. Nick, can you fix in the OS X installer?

**Comment by nriesland** [comment]
Yes, I’ll do it this morning.

**Comment by revobuil** [comment]
There isn't a build happening of the OS X installer right now because we aren't linking libraries properly. As far as I am concerned, nothing needs done on this until the more serious issues with Mac are fixed.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Mon, Aug 31, 2015 at 5:37 AM -0700, "nriesland" <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, I'll do it this morning.
